### ISSUE TITLE
Prepare cluster AMI

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#392]
To simplify submission of jobs to the cloud, we ideally should provide some lean AMI(s) for a "cluster the cloud", which we could dynamically bring up/turn down.  Eventually it should even scale dynamically ;)
AMIs should ideally be equipped with docker and singularity, and either condor or torque.
Might be worth looking inside C-PAC (https://fcp-indi.github.io/docs/user/index.html) how they orchestrate the cloud and/either they are using any batch orchestrator. Otherwise https://elasticluster.readthedocs.io/en/latest/ is probably the best bet, although ATM says that " Automated setup of: HPC clusters using SLURM or GridEngine;", so might be worth contributing if needed.

**Comment by mjtravers** [comment]
Here are some bullet points during the initial review of elasticluster

- uses the older python package boto rather than the newer boto3 to communicate with AWS
- requires python 2.7
- uses Ansible to provision nodes. Has a docker playbook and there is a PR in the project github for a singularity playbook
- PyPi has v1.2 which is quite old (~2015). The current github release version is v1.3.dev8 
- elasticluster overlaps some of the reproman functionality, such as managing running nodes/resources and keeping track of their state
- the API out of the box was broken, but not in a major way. The code does not have any automated tests

@yarikoptic 
How to you envision the cluster management to work in reproman? Using a new interface command such as "cluster"?

**Comment by yarikoptic** [comment]
Sample invocation to target 
```
$ reproman create --based-on aws-condor [--spec mysoftware.yaml] my-condor-aws-cluster num_nodes=10
```
where `aws-condor` would be a resource inventory specification which (probably) resides not in the user's inventory but in our internal one.  But they could base one cluster spec based on some other one they have.

**Comment by yarikoptic** [comment]
@mjtravers There is now a py3 conversion PR for elasticluster: https://github.com/gc3-uzh-ch/elasticluster/pull/623  It would be really valuable if you gave it a try/provided feedback.
