### ISSUE TITLE
setup_support.py is missing from pypi install

### ISSUE THREAD

**Issue by jdkent** [ReproNim/reproman#570]
`pip install reproman` currently results in the following output on my machine:

```
    ERROR: Command errored out with exit status 1:
     command: /home/jdkent/projects/ABCDRepronimHub/.repronim_tst/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ppxe7taf/reproman/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ppxe7taf/reproman/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ppxe7taf/reproman/pip-egg-info
         cwd: /tmp/pip-install-ppxe7taf/reproman/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ppxe7taf/reproman/setup.py", line 20, in <module>
        from setup_support import BuildManPage
    ModuleNotFoundError: No module named 'setup_support'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

and when I downloaded and looked at the [pypi files](https://pypi.org/project/reproman/#files), it looks like setup_support.py is not a part of the bundle.

I can get around by directly installing from the tag on github: `pip install git+https://github.com/ReproNim/reproman.git@v0.4.0`

**Comment by yarikoptic** [comment]
heh, this is annoying... it is the same issue as we have addressed in datalad awhile back "more properly": https://github.com/datalad/datalad/pull/4782 . But I only can wonder in which local environment I have produced that upload for pypi since I do have setuptools_scm installed system wide.  For now/this one, I have just minted a new release and reuploaded making sure that it has setup_tools.py and that it installs fine on some arbitrary aluminum case.  Thanks for the alert.  Let's consider it fixed with 8277a6d0cfc799312dfa635debddf3f798d8fb0d .
